"""new DB fields for GV and BC 2015

Revision ID: 2a6d1059c519
Revises: 1a6cbb61c557
Create Date: 2015-04-23 22:40:45.466937

"""

# revision identifiers, used by Alembic.
revision = '2a6d1059c519'
down_revision = '1a6cbb61c557'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('email_invite_date_bcgv15', sa.DateTime(), nullable=True))
    op.add_column('members', sa.Column('email_invite_flag_bcgv15', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'email_invite_flag_bcgv15')
    op.drop_column('members', 'email_invite_date_bcgv15')
    ### end Alembic commands ###
