"""towards merge

Revision ID: 35c80a305f9d
Revises: 4954e1458d94
Create Date: 2014-07-26 19:47:05.827890

"""

# revision identifiers, used by Alembic.
revision = '35c80a305f9d'
down_revision = '4954e1458d94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('date_of_acquisition', sa.DateTime(), nullable=False),
    sa.Column('reference_code', sa.Unicode(length=255), nullable=True),
    sa.Column('signature_received', sa.Boolean(), nullable=True),
    sa.Column('signature_received_date', sa.DateTime(), nullable=True),
    sa.Column('signature_confirmed', sa.Boolean(), nullable=True),
    sa.Column('signature_confirmed_date', sa.DateTime(), nullable=True),
    sa.Column('payment_received', sa.Boolean(), nullable=True),
    sa.Column('payment_received_date', sa.DateTime(), nullable=True),
    sa.Column('payment_confirmed', sa.Boolean(), nullable=True),
    sa.Column('payment_confirmed_date', sa.DateTime(), nullable=True),
    sa.Column('accountant_comment', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_code')
    )
    op.create_table('members_shares',
    sa.Column('members_id', sa.Integer(), nullable=False),
    sa.Column('shares_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['members_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['shares_id'], ['shares.id'], ),
    sa.PrimaryKeyConstraint('members_id', 'shares_id')
    )
    op.add_column(u'members', sa.Column('court_of_law', sa.Unicode(length=255), nullable=True))
    op.add_column(u'members', sa.Column('is_duplicate', sa.Boolean(), nullable=True))
    op.add_column(u'members', sa.Column('is_duplicate_of', sa.Integer(), nullable=True))
    op.add_column(u'members', sa.Column('registration_number', sa.Unicode(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('members') as batch_op:
        batch_op.drop_column('registration_number')
        batch_op.drop_column('is_duplicate_of')
        batch_op.drop_column('is_duplicate')
        batch_op.drop_column('court_of_law')

    op.drop_table('members_shares')
    op.drop_table('shares')
