"""removing unused memberships table

Revision ID: 39a47edfe661
Revises: 68b86fd580a
Create Date: 2014-07-18 16:29:57.073572

"""

# revision identifiers, used by Alembic.
revision = '39a47edfe661'
down_revision = '68b86fd580a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership_shares')
    op.drop_table('memberships')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memberships',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password', sa.VARCHAR(length=60), nullable=True),
    sa.Column('last_password_change', sa.DATETIME(), nullable=True),
    sa.Column('address1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('address2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('postcode', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), nullable=True),
    sa.Column('locale', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('email_is_confirmed', sa.BOOLEAN(), nullable=True),
    sa.Column('email_confirmed_date', sa.DATETIME(), nullable=True),
    sa.Column('email_confirm_code', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date_of_membership', sa.DATETIME(), nullable=False),
    sa.Column('accountant_comment', sa.VARCHAR(length=255), nullable=True),
    sa.Column('membership_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('member_of_colsoc', sa.BOOLEAN(), nullable=True),
    sa.Column('name_of_colsoc', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership_shares',
    sa.Column('membership_id', sa.INTEGER(), nullable=False),
    sa.Column('shares_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], [u'memberships.id'], ),
    sa.ForeignKeyConstraint(['shares_id'], [u'shares.id'], ),
    sa.PrimaryKeyConstraint('membership_id', 'shares_id')
    )
    ### end Alembic commands ###
