"""AfMs: token and date for membership status inquiry

Revision ID: 519d2b56f898
Revises: 4e3db989103f
Create Date: 2014-06-20 19:40:12.435961

"""

# revision identifiers, used by Alembic.
revision = '519d2b56f898'
down_revision = '4e3db989103f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('mtype_confirm_token', sa.Unicode(length=255), nullable=True))
    op.add_column('members', sa.Column('mtype_email_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'mtype_email_date')
    op.drop_column('members', 'mtype_confirm_token')
    ### end Alembic commands ###
