"""AfMs: added reminder count and date for signature and payment

Revision ID: 53f6bf273bb2
Revises: 17343990ccc0
Create Date: 2014-06-02 01:04:31.979738

"""

# revision identifiers, used by Alembic.
revision = '53f6bf273bb2'
down_revision = '17343990ccc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'members', sa.Column('sent_payment_reminder', sa.Integer(), nullable=True))
    op.add_column(u'members', sa.Column('sent_payment_reminder_date', sa.DateTime(), nullable=True))
    op.add_column(u'members', sa.Column('sent_signature_reminder', sa.Integer(), nullable=True))
    op.add_column(u'members', sa.Column('sent_signature_reminder_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'members', 'sent_signature_reminder_date')
    op.drop_column(u'members', 'sent_signature_reminder')
    op.drop_column(u'members', 'sent_payment_reminder_date')
    op.drop_column(u'members', 'sent_payment_reminder')
    ### end Alembic commands ###
