"""added date for email invitation (BC/GV 2014)

Revision ID: 68b86fd580a
Revises: 519d2b56f898
Create Date: 2014-07-11 01:51:23.957015

"""

# revision identifiers, used by Alembic.
revision = '68b86fd580a'
down_revision = '519d2b56f898'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'members', sa.Column('email_invite_flag_bcgv14', sa.Boolean(), nullable=True))
    op.add_column(u'members', sa.Column('email_invite_date_bcgv14', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'members', 'email_invite_flag_bcgv14')
    op.drop_column(u'members', 'email_invite_date_bcgv14')
    ### end Alembic commands ###
